# Generated by Django 5.2.4 on 2026-08-22 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='New Scan', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, help_text='The authenticated user who owns this chat session (null for anonymous/guest sessions).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'verbose_name_plural': 'Chat Sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], default='assistant', max_length=20)),
                ('message_type', models.CharField(choices=[('text', 'Text Message'), ('scan_result', 'URL Scan Result'), ('follow_up', 'Follow-up Response'), ('system_alert', 'System Alert')], default='text', max_length=30)),
                ('text', models.TextField(blank=True, null=True)),
                ('target_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('screenshot_path', models.CharField(blank=True, max_length=512, null=True)),
                ('screenshot_image', models.ImageField(blank=True, null=True, upload_to='screenshots/')),
                ('report', models.JSONField(blank=True, null=True)),
                ('url_analysis_data', models.JSONField(blank=True, null=True)),
                ('tool_trace', models.JSONField(blank=True, null=True)),
                ('overall_status', models.CharField(blank=True, default='COMPLETED', max_length=30, null=True)),
                ('duration_sec', models.FloatField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='agents.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentMemoryRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('namespace', models.CharField(db_index=True, max_length=255)),
                ('key', models.CharField(db_index=True, max_length=255)),
                ('value', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_memories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Memory Record',
                'verbose_name_plural': 'Agent Memory Records',
                'ordering': ['-updated_at'],
                'unique_together': {('namespace', 'key')},
            },
        ),
    ]
