# Generated by Django 5.2.4 on 2026-08-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='annotated_screenshot_data',
            field=models.TextField(blank=True, help_text='Base64 encoded annotated screenshot data URI', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='screenshot_data',
            field=models.TextField(blank=True, help_text='Base64 encoded screenshot data URI (e.g. data:image/png;base64,...)', null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='screenshot_path',
            field=models.CharField(blank=True, help_text='Legacy screenshot path or URL', max_length=512, null=True),
        ),
    ]
