# Generated by Django 5.2.4 on 2026-08-25 22:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_chatmessage_annotated_screenshot_data_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_url', models.CharField(blank=True, help_text='Target URL or domain evaluated', max_length=2048, null=True)),
                ('llm_response_summary', models.JSONField(blank=True, default=dict, help_text='Snapshot of the LLM response / report', null=True)),
                ('feedback_type', models.CharField(default='hitl_approval', help_text='Type of feedback (e.g. hitl_approval, general)', max_length=50)),
                ('responses', models.JSONField(default=dict, help_text='Question-by-question user selections and custom feedback')),
                ('rating', models.IntegerField(blank=True, help_text='Overall numerical rating (if provided)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat', models.ForeignKey(blank=True, help_text='Associated chat session if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='agents.chatsession')),
                ('message', models.ForeignKey(blank=True, help_text='The specific chat message / LLM answer being evaluated.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='agents.chatmessage')),
                ('user', models.ForeignKey(blank=True, help_text='The authenticated user submitting feedback (null for anonymous/guest sessions).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Feedback',
                'verbose_name_plural': 'User Feedbacks',
                'ordering': ['-created_at'],
            },
        ),
    ]
